### ISSUE TITLE
App not starting on macos 12.6 (Intel)

### ISSUE THREAD

**Issue by kanapka94** [kkoomen/pointless#14]
Referring to the title of the issue - app is not starting.

**Comment by kkoomen** [comment]
I'm not a wizard who can magically solve this without any information. If you're using [v1.1.0](https://github.com/kkoomen/pointless/releases/tag/v1.1.0) then obviously this won't work for Intel, as I built it manually and I use Apple Silicon (M2).

You can do a manual build for now, because that will always be built for your system specifically. Next time provide some useful information about your system, errors, warnings, screenshots or a video, as well as the version of the program you're trying to run.

**Comment by kanapka94** [comment]
Lol. Did I write somewhere that I report to the omniscient wizard?  I found the information I posted in the thread sufficient. I am reporting my 1st issue ever, so please move the second paragraph to the issue writing guidelines and don't treat others on a "guess" basis, because I took you very wrong.

P.S. In v.1.1 you have it written that you added cross-platform support, so here too it would be useful to specify what you mean.

![SCR-20221102-bx3](https://user-images.githubusercontent.com/7600593/199428052-d20f7ddb-e48d-44ff-b848-ba12820dddb3.png)
