### ISSUE TITLE
[Feature Request] Additional Tooltips

### ISSUE THREAD

**Issue by kakajuro** [kkoomen/pointless#72]
Hi, I just noticed that the buttons for help, export and paper info have no tooltips. 
I don't know if this was intentional but I thought it might be worth adding since all the other buttons have tooltips. I don't mind implementing this too if you are ok with that. The program is great so far by the way!

![image](https://github.com/kkoomen/pointless/assets/68352336/90b2d69c-ca94-4f1b-9e62-53b26ac47c1e)

**Comment by kkoomen** [comment]
It is intentional yes. Tooltips these days function as giving additional information that wouldn't be obvious by itself.

For example: When hovering over a title element that allows a double-click-to-edit functionality is something lots of people won't guess. There needs at least some visual to show hinting at the possibility of this feature. One could show a small pencil next to the text to show this visual cue. I personally enjoy a "double click to edit" tooltip to indicate this, because it's easier to implement and doesn't move the element itself in side, as opposed to showing an icon next to it.

The icons you are pointing to in the canvas are intentionally left without any tooltips, as these are common meanings for people these days. We all know these three icons represent `help`, `export` and `info` respectively. I can agree the second one can also be `upload`, but once you click on it, it's quite obvious it's an export tool. There's no extra hidden information here that people need that can't be inferred otherwise, therefore, there is no need to add tooltips here.

Thanks for bringing it up anyways, always appreciated!

**Comment by kakajuro** [comment]
Ah I see, I imagined this might be the case. Thanks for the quick response!
